name: Deloy to AWS

on:
  # Manual trigger (only allowed on dev branch)
  workflow_dispatch:

  # Automatic trigger on commits to main
  # (All commits to main will be PR merges)
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::770214659717:role/hugo-blog-deployment-bot
          role-session-name: GitHubActions
          aws-region: eu-west-2
          audience: sts.amazonaws.com

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.11.4
          aws-region: eu-west-2

      - name: Terraform Init
        run: terraform init

      - name: Determine Deployment Environment
        #   id: deployment_env
        # run: echo "deployment_env=$(echo ${{ github.ref }} | sed 's/refs\/heads\///')" >> $GITHUB_ENV
        run: echo "deployment_env=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Debug
        run: echo ${{ env.BRANCH_NAME }}

      - name: Terraform Plan
        run: terraform plan
        working-directory: ./infra
        env:
          environment_name: ${{ env.deployment_env }}

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
      #   working-directory: ./infra
